### ISSUE TITLE
Any idea why I get this? 

### ISSUE THREAD

**Issue by Rjrunner44** [umidbekk/prettier-plugin-prisma#5]
thx
<img width="615" alt="Screen Shot 2021-03-05 at 2 58 44 PM" src="https://user-images.githubusercontent.com/46289259/110183347-88136800-7dc3-11eb-913f-ae0370f8eb8f.png">

**Comment by umidbekk** [comment]
@Rjrunner44 hey, it can be a syntax error in the `.prisma` file or the version mismatch with the `prisma-engine`. 

Can you provide `prettier` output for the `npx prettier --write packages/address-book/prisma/schema.prisma`

**Comment by Rjrunner44** [comment]
not sure. I have 2 diff projects, one it formats .prisma just fine, another I get the error above. Same exact VS CODE env also. Same pretty much everything (same prisma, etc, etc)...and if I copy a xx.prisma file from one to the other, one formats and one doesn't (i.e. a good prisma file formats on one but not the other). Wish I had more to go on lol 🤷‍♂️😅 In other words, it's not the .prisma file itself that is the issue.

**Comment by Rjrunner44** [comment]
ah, there is one diff between the 2 repo projects: 1 is a normal repo (package.json at root) and the other is a lerna monorepo. Maybe that is affecting this somehow

**Comment by Rjrunner44** [comment]
if I run npx prettier --write ./prisma/schema.prisma in the sub repo, I get:

prisma/schema.prisma
[error] prisma/schema.prisma: TypeError: Cannot create property 'tokens' on string 'generator client {
[error]   provider = "prisma-client-js"
[error] }
[error] 
[error] datasource db {
[error]   provider = "postgresql"
[error]   url      = env("DATABASE_URL")
[error] }
[error] 
[error] model Message {
[error]   id          Int      @id @default(autoincrement())
[error]   fqcn String
[error]   payload String
[error]   signature String
[error]   createdAt   String
[error]   defaultTimeout   String
[error] }'
[error]     at attachComments (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:13244:14)
[error]     at coreFormat (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:13270:21)
[error]     at format (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:13516:73)
[error]     at formatWithCursor (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:13532:12)
[error]     at Object.formatWithCursor (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:44213:15)
[error]     at format$1 (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:45598:19)
[error]     at /Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:45792:16
[error]     at /Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:45731:14
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (/Users/rj/Projects/ew/ewai/messaging/packages/archive-manager/node_modules/prettier/bin-prettier.js:45730:15)

**Comment by Rjrunner44** [comment]
I upgraded the versions in the repo which didn't work to the repo which does work to be exactly the same, but the issue persists:

        "prettier": "^2.2.1",
        "prettier-plugin-prisma": "^0.4.0",

again, the only diff is one is a lerna monorepo and one is not. Thanks.

**Comment by Rjrunner44** [comment]
note: I tried prettier-plugin-prisma 0.5.0 also, no change

**Comment by umidbekk** [comment]
@Rjrunner44 I could reproduce this bug by downgrading prettier version to `v1`. 

Could you provide the output of these commands, I guess some old prettier version in hidden somewhere

- `npx yarn-why prettier`
- `npx yarn-why prettier-plugin-prisma`

**Comment by Rjrunner44** [comment]
Who required prettier:

  address-book > prettier@2.2.1


  Who required prettier-plugin-prisma:

  address-book > prettier-plugin-prisma@0.5.0

**Comment by Rjrunner44** [comment]
I have an idea. why not pick out the prettier version that your plugin sees at runtime and spit out a log/exception if ver# is too low?

**Comment by umidbekk** [comment]
@Rjrunner44 should be fixed in [v0.5.1](https://github.com/umidbekk/prettier-plugin-prisma/releases/tag/v0.5.1)

**Comment by Rjrunner44** [comment]
thx. however it is unchanged in behavior (in my monorepo), same error. Thanks for taking a look though, appreciated.

        "prettier": "^2.2.1",
        "prettier-plugin-prisma": "^0.5.1",
