### ISSUE TITLE
Auto formatting is working but auto completion(like relation) is not working

### ISSUE THREAD

**Issue by githong-kr** [umidbekk/prettier-plugin-prisma#62]
**Describe the bug**
Auto formatting is working but auto completion(like relation) is not working

**Expected behavior**

**Tools (please provide the output of the following commands):**
macOS, vscode, prettier-plugin-prisma v3.10, prisma v3.10

- Node version: v14.17.6
- OS name: macOS,
- Installed prettier versions: v8.1.0
- Installed plugin versions: v3.10

![스크린샷 2022-03-01 오후 1 15 32](https://user-images.githubusercontent.com/75356242/156103795-55de1bb4-67b0-4d7c-8d92-3272d975edb8.png)

**Comment by githong-kr** [comment]
@umidbekk
Hi~ Thanks for reply and Sorry for late.

I found the case that auto completion ( like relation )

I used [Refreential integrity](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity) of Prisma

**example of setting the referential integrity**
```
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator js {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}
```

And I found that the problem is `referentialIntegrity = "prisma"` statement

If I remove the statement, auto completion is working!!

https://user-images.githubusercontent.com/75356242/158019004-8703a636-cd1f-442b-bfcc-76943fb89d7d.mov


https://user-images.githubusercontent.com/75356242/158019010-971a512f-2dc6-4b89-9039-4622254222d8.mov

!

**Comment by umidbekk** [comment]
Hey @githong-kr, `referentialIntegrity` is still in preview, so I guess that's why it's not fully covered by formatter, I suggest you to leave comment in https://github.com/prisma/prisma/issues/9380

cc @tomhoule 🙏
