### ISSUE TITLE
useTabs seems to not be respected

### ISSUE THREAD

**Issue by Arteneko** [umidbekk/prettier-plugin-prisma#66]
With the following .prettierrc.json configuration, I get proper tabs on all ts files, but not prisma, where I get 4 spaces instead.

```json
{
	"useTabs": true,
	"tabWidth": 4,
	"semi": true,
	"singleQuote": true,
	"trailingComma": "all",
	"printWidth": 120
}
```

Am I missing something?

1. Using this config, make a prisma file with fucked up indent
2. Use `prettier ./file.prisma`

**Expected behavior**

Formatting would end up as tabs

**Tools (please provide the output of the following commands):**

- Node version: v17.9.0
- OS name: Arch-linux
- Installed prettier versions: 2.6.2
- Installed plugin versions: 3.13.0

**Comment by umidbekk** [comment]
Hey @Arteneko ! `prisma-fmt` only supports [`tab_width`](https://github.com/prisma/prisma-engines/blob/main/prisma-fmt/src/lib.rs#L35-L45) parameter and therefore [Supported Options](https://github.com/umidbekk/prettier-plugin-prisma#supported-options) are limited

**Comment by Arteneko** [comment]
Do you intend to support tabs at some point?
