### ISSUE TITLE
not working when trying to use with prettier.format function ?

### ISSUE THREAD

**Issue by liesislukas** [umidbekk/prettier-plugin-prisma#70]
I have schema code built by other tools i build and in this use case i want to have a function where i can provide generated code and get nice formatted schema to write to schema file.

I tried @umidbekk plugin but it failed to do the job with error which seem like prettier is looking like prettier thinks it's javascript, while it's not. And i don't see any way to tell prettier that it's prisma schema. Any hints?

```
  const prettier = require("prettier");
  let result = prettier.format(code, {
      parser: "babel", plugins: ["prettier-plugin-prisma"]
    });
```

![image](https://user-images.githubusercontent.com/2733862/183937535-d7588c75-d2dd-4f9d-85e6-ee660dacf367.png)

also posted at prisma repo https://github.com/prisma/prisma/issues/1761

**Comment by umidbekk** [comment]
Hey @liesislukas, you're using `babel` parser, so prettier thinks that you're parsing the ES file.

Passing the `prisma` parser should work.
