### ISSUE TITLE
[improvement] Support @map and @@map

### ISSUE THREAD

**Issue by bperel** [umidbekk/prettier-plugin-prisma#71]
Thank you for this plugin.

Is there a chance that you could support the `@map` and `@@map` instructions, as defined [here in the Prisma documentation](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map)? Where my Prisma file contains `@map`, the plugin reformats the file like this:
```
model users {
  id                        Int                         @id @default(autoincrement()) @map("ID")
  username                  String                      @unique(map: "username") @db.VarChar(25)
  password                  String                      @db.VarChar(40)
  allowSharing              Boolean                     @default(true) @map("AccepterPartage")
}
```

where I would expect something like: 
```
model users {
  id                        Int                         @id @default(autoincrement())             @map("ID")
  username                  String                      @unique(map: "username") @db.VarChar(25)
  password                  String                      @db.VarChar(40)
  allowSharing              Boolean                     @default(true)                            @map("AccepterPartage")
}
```

**Comment by umidbekk** [comment]
Hey @bperel! This plugin is built on top of [@prisma/prisma-fmt-wasm](https://github.com/prisma/prisma-fmt-wasm), which is built from the `prisma-fmt` lib from the [prisma-engines](https://github.com/prisma/prisma-engines).

I suggest you to forward your request there.
