### ISSUE TITLE
Use this for code blocks instead of Prisma schema files?

### ISSUE THREAD

**Issue by janpio** [umidbekk/prettier-plugin-prisma#9]
Is there a way to use this for code blocks inside larger documents like documentation?

For example:
```` 
```prisma
model Foo {
  id          Int @id
}
```
````  

We would be pretty interested for https://www.prisma.io/docs/ honestly 😄

**Comment by umidbekk** [comment]
@janpio looks like it was working already https://github.com/umidbekk/prettier-plugin-prisma/blob/abc3faeb3f14658a083fdcd142911485f5d545e8/test/plugin.spec.js#L47-L94

I've checked in https://github.com/prisma/docs and add PR too https://github.com/prisma/docs/pull/1985

**Comment by janpio** [comment]
Wow, I wondered what we messed up in our testing then. Thanks so much!
